# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d082b78a3deb2ce7e76f1a108a6473da01b0828f3483bf905bfa6f050e9d91a93518d7e62feb7e1f8e0800b786ddc848563481f1a2067eb75e7a7135283c08f

test:
  secret_key_base: c4511f005e55866a8cb7f65fd52a28a9993aa37a4694b95ec0b3a9f19c2f240c5175dc226bf5579500f2db5b15b8ae560e3c482e7cb62feecfb68e99ad0b31a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
